### PR TITLE
Added Fable Lore Section and Couple of Mods

### PR DESCRIPTION
**Pull request by Rage-GitHub**

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
please link to the original sources for file hosts like mega/gdrive etc

**Comment by Rage-GitHub** [comment]
> please link to the original sources for file hosts like mega/gdrive etc

Sorry, what do you mean by this?

**Comment by EzioTheDeadPoet** [comment]
> > please link to the original sources for file hosts like mega/gdrive etc
> 
> Sorry, what do you mean by this?

Link the source where you found this link:
https://mega.nz/file/haoBFLAB#Bka9McxP2JiYrim2_n2djTib_zHVdK38VbkwiH116Hk # dTry's Key Utils NG 
and any similar to it. Cause otherwise we can't verify the legitimacy of the source and therefore can't whitelist it.

**Comment by Rage-GitHub** [comment]
As mentioned in the commit, it is a sticky post on the original mod page on Nexus that is an approved version by the original MA.
https://www.nexusmods.com/skyrimspecialedition/mods/69944?tab=posts

**Pull request merged**
