### PR TITLE
ServerWhitelist.yml

### PR DESCRIPTION
**Pull request by CJGamerX**
Looking to complete a relatively simplistic enhanced cut content modlist. Want these mods in my modlist due to some of them providing a more updated experience.

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
links are missing origins for the sources to verify that they aren't pirated.

**Comment by vensko** [comment]
Cyberware 2281 is posted exclusively on ModPub under a [private use](https://mod.pub/build/license/MPNC-1.0.txt) license https://mod.pub/falloutnv/15-cyberware-2281

You cannot upload it anywhere and call it legal.

**Comment by eddoursul** [comment]
Cyberware 2281 is posted exclusively on ModPub under a private use license https://mod.pub/falloutnv/15-cyberware-2281

You cannot upload it anywhere and call it legal.

**Comment by EzioTheDeadPoet** [comment]
Then we could add mod.pub to the whitelist and people can use `manualURL`.

**Comment by TDarkShadow** [comment]
> Then we could add mod.pub to the whitelist and people can use `manualURL`.

`Unauthorized automated mass downloading of mods is not allowed and may result in account suspension. This includes the use of Wabbajack, userscripts, bots, and other methods. Distribution of materials, accomodating automated mass downloading, is not allowed. `

https://mod.pub/terms-of-service#user-content

**Comment by EzioTheDeadPoet** [comment]
I mean it isn't mass downloading with WJ but oof dumb website spotted. It is the same as if users download it manually with their own browser and clicking thru the pages.

**Comment by EzioTheDeadPoet** [comment]
But considering that some new list authors would probably f it up and use a bad link in their meta that isn't manual URL based I guess I won't whitelist it until I had a look at their official api that seems to be coming.

**Pull request closed without merging**
