### PR TITLE
Update ServerWhitelist.yml

### PR DESCRIPTION
**Pull request by JmyX420**
Server Mods and Asset Archives required for New Vegas: Multiplayer (NV:MP)
I am a NV:MP staff member and I have permission from the head dev.

### CODE REVIEW

**Comment by JmyX420** [comment]
@JanuarySnow sorry to bother you, could you merge this when you get a chance please?

**Comment by JmyX420** [comment]
@TDarkShadow Sorry to bother you, would you merge this when you get a chance please?

**Comment by TDarkShadow** [comment]
Looks good to me but I have yet to check if they contain any copyrighted material from FNV archives.

**Comment by JmyX420** [comment]
Ok thank you, if any of the bsa's are an issue I can remove them. Our launcher can handle downloading them.

**Comment by JmyX420** [comment]
any word on this?

**Pull request merged**
