### PR TITLE
Update ServerWhitelist.yml

### PR DESCRIPTION
**Pull request by Patchier**
add google id for one of my texture mods

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
Did you create those assets?

**Comment by Patchier** [comment]
Oh god no. I just mean texture mods I'm using. I'm not skilled enough to create stuff like this.

**Comment by EzioTheDeadPoet** [comment]
Then we need an URL in this conversation to where that GDrive link comes from to verify that it is not uploaded to GDrive by an unauthorized 3rd party.

**Comment by Patchier** [comment]
> Then we need an URL in this conversation to where that GDrive link comes from to verify that it is not uploaded to GDrive by an unauthorized 3rd party.

Sure. It's at the bottom of this section of one of Qolore's modding guides: https://qolore7.github.io/bluemoon/creaturetextures.html

**Pull request merged**
