### PR TITLE
Added Impactful Blocking

### PR DESCRIPTION
**Pull request by Rage-GitHub**
Skyrim Guild websites domain changed to Modding Guild.

### CODE REVIEW

**Comment by TDarkShadow** [comment]
Already whitelisted as per  #781.

**Comment by Rage-GitHub** [comment]
Weird, I keep getting a no access allowed for the download when using the new domain.

**Comment by TDarkShadow** [comment]
> Weird, I keep getting a no access allowed for the download when using the new domain. 

Can you share your meta and Wabbajack log of the failed compilation here for the mod that fails? Could be a subdomain issue.

**Comment by Rage-GitHub** [comment]
> > Weird, I keep getting a no access allowed for the download when using the new domain.
> 
> Can you share your meta and Wabbajack log of the failed compilation here for the mod that fails? Could be a subdomain issue.

Sorry, I might be passed this now. The author decided to swap out the the mod for another one, but let me see.

**Comment by Rage-GitHub** [comment]
> > Weird, I keep getting a no access allowed for the download when using the new domain.
> 
> Can you share your meta and Wabbajack log of the failed compilation here for the mod that fails? Could be a subdomain issue.

[Wabbajack.08.log](https://github.com/wabbajack-tools/opt-out-lists/files/13393759/Wabbajack.08.log)

**Pull request closed without merging**
